site_name: Machine Learning
site_url: https://mgabriel4.github.io/machine-learning-grupo4/
repo_url: https://github.com/mgabriel4/machine-learning-grupo4
repo_name: machine-learning-grupo4

theme:
  name: material
  palette:
    # primary: grey
    # Light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: orange
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
  navigation:
    expand: false
  icon:
    # logo: assets/images/devops
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - markdown_grid_tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true  
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - tables
      
plugins:
  # - git-committers:
  #     repository: snowdutra/Machine-Learning
  #     branch: main
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  # - git-authors
  - search
  - badges
  - minify:
      minify_html: true
  - markdown-exec
  - render_swagger:
      allow_arbitrary_locations : true
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra_javascript:
  - https://unpkg.com/mathjax/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js

nav:
  - Home: ./index.md
  - Árvore de Decisão:
    - 01 - Exploração: ./arvore_decisao/01_exploracao.md
    - 02 - Pré-processamento: ./arvore_decisao/02_preprocessamento.md
    - 03 - Divisão treino/teste: ./arvore_decisao/03_divisao.md
    - 04 - Treinamento: ./arvore_decisao/04_treinamento.md
    - 05 - Avaliação: ./arvore_decisao/05_avaliacao.md
    - 06 - Visualização: ./arvore_decisao/06_visualizacao.md
  - KNN:
    - 01 - Exploração: ./knn/01_exploracao.md
    - 02 - Pré-processamento: ./knn/02_preprocessamento.md
    - 03 - GridSearch: ./knn/03_elbow_silhouette.md
    - 04 - Treinamento: ./knn/04_treinamento.md
    - 05 - Visualização: ./knn/05_visualizacao.md
  - KMeans:
    - 01 - Exploração: ./kmeans/01_exploracao.md
    - 02 - Pré-processamento: ./kmeans/02_preprocessamento.md
    - 03 - Elbow e Silhouette: ./kmeans/03_elbow_silhouette.md
    - 04 - Treinamento: ./kmeans/04_treinamento.md
    - 05 - Visualização: ./kmeans/05_visualizacao.md
  - Relatório Final: ./relatorio_final/relatorio_final.md